services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      TZ: Europe/Paris
      LANG: fr_FR.UTF-8
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: back_actumatic
    restart: unless-stopped
    depends_on:
      - postgres
    secrets:
      - database_url
    ports:
      - '3000:3000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: front_actumatic
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  postgres_data:
    driver: local

secrets:
  postgres_user:
    file: secrets/postgres_user
  postgres_password:
    file: secrets/postgres_password
  postgres_db:
    file: secrets/postgres_db
  database_url:
    file: secrets/database_url
